
name: CI Pipeline - Intranet NewDeal

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: 1.0.0
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:


  # ==============================
  # JOB 1 - CI : BUILD + PUSH + SCAN
  # ===============================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      - name: Verify image
        run: |
          docker image ls | grep $IMAGE_NAME
  scan:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Build image again
        run: |
          docker build -t intranet-newdeal:1.0.0 .
  
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: intranet-newdeal:1.0.0
          format: table
          exit-code: 0
    

  push:
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
  
      - name: Push image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG


  #hnbv;cn ,n
