name: CD Pipeline - Production

on:
  push:
    branches:
      - prod

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: 1.0.0

jobs:

  # 🔹 1. SCAN SÉCURITÉ
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1   # 🔥 bloque si vulnérabilité critique


