name: CD Pipeline - Production

on:
  push:
    branches:
      - prod

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: latest
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  # ===============================
  # JOB 1 - SECURITY SCAN
  # ===============================
  scan:
    name: scan security 
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Run Trivy scan (BLOCK CRITICAL)
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL
          vuln-type: os,library
          ignore-unfixed: true
          exit-code: 1

  # ===============================
  # JOB 2 - DEPLOYMENT
  # ===============================
  deploy:
    name: Deployment
    needs: scan
    runs-on: ubuntu-latest

    steps:
      - name: Pull image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Run container (simulation)
        run: |
          docker run -d -p 80:80 --name intranet-prod \
          $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Verify container
        run: |
          docker ps
